---
title: "etn owf exploration"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Data exploration of European Tracking Network data inside European Offshore Wind Farms

## Setup

### workspace

R packages

```{r pgk}
library(dplyr)
# library(magrittr)
library(sf)
library(purrr)
library(lubridate)

library(tidyr)
library(ggplot2)
# library(plotly)

library(leaflet)
library(mapview)
# library(mgcv)

# install.packages("pak")
# pak::pak("inbo/etn")

library(etn)
```

Loading functions

```{r fun}
source("R/helpers.R")
```

Setting paths

```{r var}
path_spatial <- "data/spatial"
path_data_raw <- "data_raw"
```

### loading spatial data

```{r data-spatial}
load_files_to_env(path = path_spatial, file_ext = "gpkg")

# fix owf polygons
## TODO: put into spatial data script
windfarms_polygons <- windfarms_polygons %>% sf::st_make_valid()

windfarms_polygons_union <- 
  windfarms_polygons %>%
  group_by(country) %>%
  summarise(geom = st_union(geom))

windfarms_polygons_prod <- 
  windfarms_polygons %>%
  dplyr::filter(status == 'Production')
```

## ETN data

```{r etn-con}
## connect to ETN R package
if(packageVersion('etn') >= "2.3.0"){
  # if 'new' version of etn R package: read .Renviron directly
  readRenviron(".Renviron")
  Sys.getenv("ETN_USER")
  Sys.getenv("ETN_PWD")
}else{
  # if 'old' version: create con object
  con <- etn::connect_to_etn(Sys.getenv("ETN_USER"), Sys.getenv("ETN_PWD"))}
```


### acoustic receiver deployments

```{r etn-deployments}
deployments_raw <-  etn::get_acoustic_deployments()
save_data(deployments_raw, folder = path_data_raw)


deployments <-
  deployments_raw %>%
  # remove deployments with missing lat or lon
  dplyr::filter(!is.na(deploy_latitude) | !is.na(deploy_longitude)) %>%
  # transform lat/lon into geom
  dplyr::mutate(lat = deploy_latitude,
                lon = deploy_longitude) %>%
  sf::st_as_sf(., coords = c("lon", "lat"), crs = 4326) %>%
  # make new col with boolean that is TRUE if inside OWF
  dplyr::mutate(inside_OWF = lengths(sf::st_within(geometry, windfarms_polygons_prod)) > 0) %>%
  sf::st_join(windfarms_polygons_prod, join = sf::st_within) %>% 
  # remove duplicated deployments
  dplyr::distinct(deployment_id, .keep_all = T)
```

